# Generated by Django 3.2.11 on 2022-02-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_placemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemodel',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='placemodel',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
