# Generated by Django 3.2.11 on 2022-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_placemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecomment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
